locals {
  vercel_team_id = try(var.vercel_project.team_id, null)

  supabase_enabled = var.supabase_project != null

  supabase_settings_enabled = local.supabase_enabled && (
    try(var.supabase_project.api_settings, null) != null ||
    try(var.supabase_project.auth_settings, null) != null ||
    try(var.supabase_project.database_settings, null) != null ||
    try(var.supabase_project.network_settings, null) != null ||
    try(var.supabase_project.pooler_settings, null) != null ||
    try(var.supabase_project.storage_settings, null) != null
  )

  supabase_env_enabled = local.supabase_enabled && try(var.supabase_to_vercel.enabled, true)

  supabase_project_ref = local.supabase_enabled ? supabase_project.this[0].id : null
  supabase_url         = local.supabase_enabled ? "https://${local.supabase_project_ref}.supabase.co" : null

  supabase_base_env = local.supabase_env_enabled ? {
    supabase-url = {
      key       = "NEXT_PUBLIC_SUPABASE_URL"
      value     = local.supabase_url
      target    = try(var.supabase_to_vercel.targets, ["production", "preview"])
      sensitive = false
      comment   = "Generated by Terraform stack ${var.stack_name}"
    }
  } : {}

  supabase_publishable_env = local.supabase_env_enabled && try(var.supabase_to_vercel.include_publishable_key, true) ? {
    supabase-publishable-key = {
      key       = "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
      value     = data.supabase_apikeys.this[0].publishable_key
      target    = try(var.supabase_to_vercel.targets, ["production", "preview"])
      sensitive = true
      comment   = "Generated by Terraform stack ${var.stack_name}"
    }
  } : {}

  supabase_legacy_anon_env = local.supabase_env_enabled && try(var.supabase_to_vercel.include_legacy_anon_key, false) ? {
    supabase-anon-key = {
      key       = "NEXT_PUBLIC_SUPABASE_ANON_KEY"
      value     = data.supabase_apikeys.this[0].anon_key
      target    = try(var.supabase_to_vercel.targets, ["production", "preview"])
      sensitive = true
      comment   = "Generated by Terraform stack ${var.stack_name}"
    }
  } : {}

  supabase_legacy_service_role_env = local.supabase_env_enabled && try(var.supabase_to_vercel.include_legacy_service_role_key, false) ? {
    supabase-service-role-key = {
      key       = "SUPABASE_SERVICE_ROLE_KEY"
      value     = data.supabase_apikeys.this[0].service_role_key
      target    = try(var.supabase_to_vercel.targets, ["production", "preview"])
      sensitive = true
      comment   = "Generated by Terraform stack ${var.stack_name}"
    }
  } : {}

  supabase_transaction_database_url_env = local.supabase_env_enabled && try(var.supabase_to_vercel.include_transaction_database_url, false) ? {
    supabase-transaction-database-url = {
      key       = "DATABASE_URL"
      value     = data.supabase_pooler.this[0].url["transaction"]
      target    = try(var.supabase_to_vercel.targets, ["production", "preview"])
      sensitive = true
      comment   = "Generated by Terraform stack ${var.stack_name}"
    }
  } : {}

  generated_vercel_environment_variables = merge(
    local.supabase_base_env,
    local.supabase_publishable_env,
    local.supabase_legacy_anon_env,
    local.supabase_legacy_service_role_env,
    local.supabase_transaction_database_url_env
  )

  vercel_environment_variables = merge(
    var.vercel_environment_variables,
    local.generated_vercel_environment_variables
  )

  primary_domain_vercel_domains = merge(
    {
      for key, domain in var.primary_domains : "${key}-apex" => {
        domain               = domain.apex_domain
        redirect             = try(domain.redirect_apex_to_canonical, true) ? coalesce(try(domain.canonical_domain, null), "www.${domain.apex_domain}") : null
        redirect_status_code = try(domain.redirect_apex_to_canonical, true) ? try(domain.redirect_status_code, 308) : null
      }
    },
    {
      for key, domain in var.primary_domains : "${key}-canonical" => {
        domain = coalesce(try(domain.canonical_domain, null), "www.${domain.apex_domain}")
      }
    }
  )

  primary_domain_cloudflare_dns_records = merge(
    {
      for key, domain in var.primary_domains : "${key}-apex" => {
        zone_id = domain.zone_id
        name    = domain.apex_domain
        type    = "A"
        content = try(domain.apex_record_content, "76.76.21.21")
        ttl     = try(domain.ttl, 1)
        proxied = try(domain.proxied, false)
        comment = "Primary apex domain for Terraform stack ${var.stack_name}"
      }
    },
    {
      for key, domain in var.primary_domains : "${key}-canonical" => {
        zone_id = domain.zone_id
        name    = coalesce(try(domain.canonical_domain, null), "www.${domain.apex_domain}")
        type    = "CNAME"
        content = try(domain.canonical_record_content, "cname.vercel-dns.com")
        ttl     = try(domain.ttl, 1)
        proxied = try(domain.proxied, false)
        comment = "Primary canonical domain for Terraform stack ${var.stack_name}"
      }
    }
  )

  vercel_domains = merge(
    local.primary_domain_vercel_domains,
    var.vercel_domains
  )

  cloudflare_dns_records = merge(
    local.primary_domain_cloudflare_dns_records,
    var.cloudflare_dns_records
  )
}

resource "vercel_project" "this" {
  name                                              = var.vercel_project.name
  framework                                         = try(var.vercel_project.framework, "nextjs")
  team_id                                           = local.vercel_team_id
  root_directory                                    = try(var.vercel_project.root_directory, null)
  build_command                                     = try(var.vercel_project.build_command, null)
  install_command                                   = try(var.vercel_project.install_command, null)
  output_directory                                  = try(var.vercel_project.output_directory, null)
  dev_command                                       = try(var.vercel_project.dev_command, null)
  node_version                                      = try(var.vercel_project.node_version, null)
  automatically_expose_system_environment_variables = try(var.vercel_project.automatically_expose_system_environment_variables, true)
  auto_assign_custom_domains                        = try(var.vercel_project.auto_assign_custom_domains, true)
  git_repository                                    = try(var.vercel_project.git_repository, null)
}

resource "supabase_project" "this" {
  count = local.supabase_enabled ? 1 : 0

  organization_id   = var.supabase_project.organization_id
  name              = var.supabase_project.name
  database_password = var.supabase_project.database_password
  region            = var.supabase_project.region
  instance_size     = try(var.supabase_project.instance_size, "micro")

  lifecycle {
    ignore_changes = [database_password]
  }
}

resource "supabase_settings" "this" {
  count = local.supabase_settings_enabled ? 1 : 0

  project_ref = supabase_project.this[0].id
  api         = try(var.supabase_project.api_settings, null) == null ? null : jsonencode(var.supabase_project.api_settings)
  auth        = try(var.supabase_project.auth_settings, null) == null ? null : jsonencode(var.supabase_project.auth_settings)
  database    = try(var.supabase_project.database_settings, null) == null ? null : jsonencode(var.supabase_project.database_settings)
  network     = try(var.supabase_project.network_settings, null) == null ? null : jsonencode(var.supabase_project.network_settings)
  pooler      = try(var.supabase_project.pooler_settings, null) == null ? null : jsonencode(var.supabase_project.pooler_settings)
  storage     = try(var.supabase_project.storage_settings, null) == null ? null : jsonencode(var.supabase_project.storage_settings)
}

data "supabase_apikeys" "this" {
  count = local.supabase_env_enabled && (
    try(var.supabase_to_vercel.include_publishable_key, true) ||
    try(var.supabase_to_vercel.include_legacy_anon_key, false) ||
    try(var.supabase_to_vercel.include_legacy_service_role_key, false)
  ) ? 1 : 0

  project_ref = supabase_project.this[0].id

  depends_on = [supabase_project.this]
}

data "supabase_pooler" "this" {
  count = local.supabase_env_enabled && try(var.supabase_to_vercel.include_transaction_database_url, false) ? 1 : 0

  project_ref = supabase_project.this[0].id

  depends_on = [supabase_project.this]
}

resource "vercel_project_environment_variable" "this" {
  for_each = toset(nonsensitive(keys(local.vercel_environment_variables)))

  project_id             = vercel_project.this.id
  team_id                = local.vercel_team_id
  key                    = nonsensitive(local.vercel_environment_variables[each.key].key)
  value_wo               = local.vercel_environment_variables[each.key].value
  target                 = nonsensitive(try(local.vercel_environment_variables[each.key].target, null))
  custom_environment_ids = nonsensitive(try(local.vercel_environment_variables[each.key].custom_environment_ids, null))
  git_branch             = nonsensitive(try(local.vercel_environment_variables[each.key].git_branch, null))
  sensitive              = nonsensitive(try(local.vercel_environment_variables[each.key].sensitive, true))
  comment                = nonsensitive(try(local.vercel_environment_variables[each.key].comment, "Managed by Terraform stack ${var.stack_name}"))
}

resource "vercel_project_domain" "this" {
  for_each = local.vercel_domains

  project_id            = vercel_project.this.id
  team_id               = local.vercel_team_id
  domain                = each.value.domain
  redirect              = try(each.value.redirect, null)
  redirect_status_code  = try(each.value.redirect_status_code, null)
  git_branch            = try(each.value.git_branch, null)
  custom_environment_id = try(each.value.custom_environment_id, null)
}

resource "cloudflare_dns_record" "this" {
  for_each = local.cloudflare_dns_records

  zone_id  = each.value.zone_id
  name     = each.value.name
  type     = upper(each.value.type)
  content  = each.value.content
  ttl      = try(each.value.ttl, 1)
  proxied  = try(each.value.proxied, false)
  priority = try(each.value.priority, null)
  comment  = try(each.value.comment, "Managed by Terraform stack ${var.stack_name}")
  tags     = try(each.value.tags, [])
  settings = try(each.value.settings, null)
}
