output "vercel_project" {
  description = "Vercel project metadata."
  value = {
    id      = vercel_project.this.id
    name    = vercel_project.this.name
    team_id = local.vercel_team_id
  }
}

output "vercel_domains" {
  description = "Attached Vercel domains."
  value = {
    for key, domain in vercel_project_domain.this : key => {
      id     = domain.id
      domain = domain.domain
    }
  }
}

output "primary_domains" {
  description = "Canonical primary domain mapping generated by the module."
  value = {
    for key, domain in var.primary_domains : key => {
      apex_domain                = domain.apex_domain
      canonical_domain           = coalesce(try(domain.canonical_domain, null), "www.${domain.apex_domain}")
      redirect_apex_to_canonical = try(domain.redirect_apex_to_canonical, true)
    }
  }
}

output "supabase_project" {
  description = "Supabase project metadata."
  value = local.supabase_enabled ? {
    ref = supabase_project.this[0].id
    url = local.supabase_url
  } : null
  sensitive = true
}

output "cloudflare_dns_records" {
  description = "Cloudflare DNS records managed by the stack."
  value = {
    for key, record in cloudflare_dns_record.this : key => {
      id      = record.id
      name    = record.name
      type    = record.type
      zone_id = record.zone_id
    }
  }
}
